### ISSUE TITLE
Low contrast on comments

### ISSUE THREAD

**Issue by lizzardsteam** [alexdo1000/Catppuccin-Noir#1]
### Description
On bigger screens comments are hard t read.

### Proposal
Comment foreground color should probably be changed to a brighter and/or different color.

**Comment by alexdo1000** [comment]
Hi @lizzardsteam , I am experimenting with a few options for the comment foreground color.

<img width="683" alt="image" src="https://github.com/user-attachments/assets/1e98d264-5e74-4b19-998e-dec12356a69b">

How does this look?

**Comment by lizzardsteam** [comment]
Hey, @alexdo1000,
From the image it looks a lot better than what I had yesterday. 
Could you tell me what the color hex so I can test it the environment where I had the issue?

**Comment by alexdo1000** [comment]
@lizzardsteam  the new color is: #757894 for comments

I published version 0.1.1 today and now the change for lighter comments is included as a second theme: 

Catppuccin Noir High Contrast 
![image](https://github.com/user-attachments/assets/6487d0ba-d812-41e3-beac-7d1e73b1ae55)

Try it out and let me know what you think

**Comment by lizzardsteam** [comment]
Hey, @alexdo1000,
The brighter comment color is great. Thank you!
